version: "3"  # docker version
services:
  www:
    image: php:apache
    volumes:
      - "./app:/var/www/html" # sync project dir with web dir
    ports:
      - 80:80
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=marvel_fans
      - MYSQL_USER=marvel
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./app:/docker-entrypoint-initdb.d" # sync persistent sql files with container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
